# Form implementation generated from reading ui file 'D:\Chuong3\BT60\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1031, 747)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 130, 411, 531))
        self.groupBox.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 255);\n"
"color: rgb(255, 0, 127);")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 391, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_list = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_list.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_list.setObjectName("verticalLayout_list")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 20, 461, 81))
        self.label.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 85, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 130, 511, 331))
        self.groupBox_2.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 170, 255);\n"
"background-color: rgb(170, 255, 255);\n"
"color: rgb(255, 0, 127);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 141, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 250, 151, 31))
        self.label_4.setObjectName("label_4")
        self.lineEdit_mssv = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_mssv.setGeometry(QtCore.QRect(170, 50, 321, 51))
        self.lineEdit_mssv.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_mssv.setObjectName("lineEdit_mssv")
        self.lineEdit_hoten = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_hoten.setGeometry(QtCore.QRect(170, 150, 321, 51))
        self.lineEdit_hoten.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_hoten.setObjectName("lineEdit_hoten")
        self.lineEdit_date = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_date.setGeometry(QtCore.QRect(170, 240, 321, 51))
        self.lineEdit_date.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_date.setObjectName("lineEdit_date")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(490, 490, 511, 171))
        self.groupBox_3.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 255, 255);\n"
"color: rgb(255, 0, 127);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonAdd.setGeometry(QtCore.QRect(50, 50, 191, 41))
        self.pushButtonAdd.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonDelete.setGeometry(QtCore.QRect(280, 50, 191, 41))
        self.pushButtonDelete.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonSearch.setGeometry(QtCore.QRect(50, 110, 191, 41))
        self.pushButtonSearch.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.pushButtonSort = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonSort.setGeometry(QtCore.QRect(280, 110, 191, 41))
        self.pushButtonSort.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButtonSort.setObjectName("pushButtonSort")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trương Võ Trường Thy"))
        self.groupBox.setTitle(_translate("MainWindow", "DANH SÁCH SINH VIÊN"))
        self.label.setText(_translate("MainWindow", "QUẢN LÝ SINH VIÊN"))
        self.groupBox_2.setTitle(_translate("MainWindow", "THÔNG TIN SINH VIÊN"))
        self.label_2.setText(_translate("MainWindow", "MSSV:"))
        self.label_3.setText(_translate("MainWindow", "HỌ & TÊN:"))
        self.label_4.setText(_translate("MainWindow", "NGÀY SINH:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "BUTTONS"))
        self.pushButtonAdd.setText(_translate("MainWindow", "ADD"))
        self.pushButtonDelete.setText(_translate("MainWindow", "DELETE"))
        self.pushButtonSearch.setText(_translate("MainWindow", "SEARCH"))
        self.pushButtonSort.setText(_translate("MainWindow", "SORT BY AGE"))
