# Form implementation generated from reading ui file 'D:\K24406H\K244060809_TruongVoTruongThy_K24406H\ui\welcomestu.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeStudent(object):
    def setupUi(self, WelcomeStudent):
        WelcomeStudent.setObjectName("WelcomeStudent")
        WelcomeStudent.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=WelcomeStudent)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 300, 40))
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_muon_sach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_muon_sach.setGeometry(QtCore.QRect(100, 80, 200, 40))
        self.btn_muon_sach.setObjectName("btn_muon_sach")
        self.btn_tra_sach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_tra_sach.setGeometry(QtCore.QRect(100, 130, 200, 40))
        self.btn_tra_sach.setObjectName("btn_tra_sach")
        self.btn_quan_ly_muon = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_quan_ly_muon.setGeometry(QtCore.QRect(100, 180, 200, 40))
        self.btn_quan_ly_muon.setObjectName("btn_quan_ly_muon")
        WelcomeStudent.setCentralWidget(self.centralwidget)

        self.retranslateUi(WelcomeStudent)
        QtCore.QMetaObject.connectSlotsByName(WelcomeStudent)

    def retranslateUi(self, WelcomeStudent):
        _translate = QtCore.QCoreApplication.translate
        WelcomeStudent.setWindowTitle(_translate("WelcomeStudent", "Xin chào Sinh viên"))
        self.btn_muon_sach.setText(_translate("WelcomeStudent", "Mượn sách"))
        self.btn_tra_sach.setText(_translate("WelcomeStudent", "Trả sách"))
        self.btn_quan_ly_muon.setText(_translate("WelcomeStudent", "Quản lý mượn sách"))
