# Form implementation generated from reading ui file 'D:\K24406H\K244060809_TruongVoTruongThy_K24406H\ui\welcometeacher.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeTeacher(object):
    def setupUi(self, WelcomeTeacher):
        WelcomeTeacher.setObjectName("WelcomeTeacher")
        WelcomeTeacher.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=WelcomeTeacher)
        self.centralwidget.setObjectName("centralwidget")
        self.label_welcome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(50, 20, 300, 40))
        self.label_welcome.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.btn_muon_sach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_muon_sach.setGeometry(QtCore.QRect(100, 80, 200, 40))
        self.btn_muon_sach.setObjectName("btn_muon_sach")
        self.btn_tra_sach = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_tra_sach.setGeometry(QtCore.QRect(100, 130, 200, 40))
        self.btn_tra_sach.setObjectName("btn_tra_sach")
        self.btn_quan_ly_muon = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_quan_ly_muon.setGeometry(QtCore.QRect(100, 180, 200, 40))
        self.btn_quan_ly_muon.setObjectName("btn_quan_ly_muon")
        WelcomeTeacher.setCentralWidget(self.centralwidget)

        self.retranslateUi(WelcomeTeacher)
        QtCore.QMetaObject.connectSlotsByName(WelcomeTeacher)

    def retranslateUi(self, WelcomeTeacher):
        _translate = QtCore.QCoreApplication.translate
        WelcomeTeacher.setWindowTitle(_translate("WelcomeTeacher", "Xin chào Giảng viên"))
        self.label_welcome.setText(_translate("WelcomeTeacher", "Xin chào Giảng viên"))
        self.btn_muon_sach.setText(_translate("WelcomeTeacher", "Mượn sách"))
        self.btn_tra_sach.setText(_translate("WelcomeTeacher", "Trả sách"))
        self.btn_quan_ly_muon.setText(_translate("WelcomeTeacher", "Quản lý mượn sách"))
